# Generated by Django 4.2.3 on 2023-09-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0042_alter_analyticview_created_by_and_more'),
        ('db', '0042_alter_issuevote_unique_together_alter_issuevote_vote_and_more'),
    ]

    operations = [
    ]
